"""Create Game Model

Revision ID: 88d9a049a25b
Revises: 88b18713da86
Create Date: 2023-12-10 00:34:06.414489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d9a049a25b'
down_revision = '88b18713da86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
